/**
 * Data access layer for the digital garden.
 *
 * Reads from pre-generated JSON files (src/data/notes.json) instead of a
 * database. This allows the site to run on serverless platforms (Vercel,
 * Netlify) without a database — the JSON files are bundled with the build.
 *
 * The JSON files are generated by `bun run publish` (scripts/publish.ts).
 */

import type { WikiLinkTarget } from "@/lib/markdown";

// --- Types ---

interface NoteRecord {
  slug: string;
  title: string;
  description: string | null;
  content: string;
  html: string;
  raw: string;
  tags: string[];
  aliases: string[];
  links: WikiLinkTarget[];
  wordCount: number;
  draft: boolean;
  publishDate: string | null;
  createdAt: string;
  updatedAt: string;
  path: string;
  folder: string | null;
}

export interface NoteSummary {
  slug: string;
  title: string;
  description: string | null;
  tags: string[];
  aliases: string[];
  wordCount: number;
  publishDate: string | null;
  createdAt: string;
  updatedAt: string;
  path: string;
  folder: string | null;
}

export interface RelatedNote extends NoteSummary {
  reason: "shared-tags" | "2-hop" | "shared-links";
  score: number;
}

export interface BacklinkNote extends NoteSummary {
  context: string | null;
}

export interface NoteDetail extends NoteSummary {
  content: string;
  html: string;
  links: WikiLinkTarget[];
  backlinks: BacklinkNote[];
  related: RelatedNote[];
  prev: NoteSummary | null;
  next: NoteSummary | null;
}

export interface GraphNode {
  id: string;
  title: string;
  tags: string[];
  folder: string | null;
}

export interface GraphEdge {
  source: string;
  target: string;
}

export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface TagInfo {
  tag: string;
  count: number;
}

export interface ExplorerNode {
  name: string;
  path: string;
  type: "folder" | "file";
  slug?: string;
  children?: ExplorerNode[];
}

// --- Data loading ---

// Import the JSON data. This is bundled at build time.
import notesData from "@/data/notes.json";

const NOTES: NoteRecord[] = notesData as NoteRecord[];

// --- Helpers ---

function toSummary(n: NoteRecord): NoteSummary {
  return {
    slug: n.slug,
    title: n.title,
    description: n.description,
    tags: n.tags,
    aliases: n.aliases,
    wordCount: n.wordCount,
    publishDate: n.publishDate,
    createdAt: n.createdAt,
    updatedAt: n.updatedAt,
    path: n.path,
    folder: n.folder,
  };
}

/**
 * Extract the sentence context around a wikilink reference.
 */
function extractBacklinkContext(
  content: string,
  targetTitle: string,
  targetAliases: string[] = []
): string | null {
  const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const names = [targetTitle, ...targetAliases].filter(Boolean).map(escapeRe);
  if (names.length === 0) return null;
  const patterns = names.map(
    (n) => new RegExp(`\\[\\[\\s*${n}\\s*[|#\\]]`, "i")
  );
  const sentences = content
    .replace(/\n+/g, " ")
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 10);
  for (const pattern of patterns) {
    for (const sentence of sentences) {
      if (pattern.test(sentence)) {
        const cleaned = sentence
          .replace(/\[\[([^\]|#]+)(?:\|[^\]]*)?\]\]/g, "$1")
          .replace(/\s+/g, " ")
          .trim();
        return cleaned.length > 180 ? cleaned.slice(0, 177) + "…" : cleaned;
      }
    }
  }
  return null;
}

// --- Queries ---

export async function listNotes(opts?: {
  tag?: string;
  folder?: string;
  limit?: number;
  sort?: "newest" | "oldest" | "alpha" | "updated";
}): Promise<NoteSummary[]> {
  const { tag, folder, limit, sort = "newest" } = opts ?? {};
  let filtered = NOTES;
  if (folder) filtered = filtered.filter((n) => n.folder === folder);
  if (tag) filtered = filtered.filter((n) => n.tags.includes(tag));
  const sorted = [...filtered].sort((a, b) => {
    if (sort === "alpha") return a.title.localeCompare(b.title);
    if (sort === "oldest")
      return (
        (a.publishDate ?? a.createdAt).localeCompare(b.publishDate ?? b.createdAt)
      );
    if (sort === "updated") return b.updatedAt.localeCompare(a.updatedAt);
    return (b.publishDate ?? b.createdAt).localeCompare(
      a.publishDate ?? a.createdAt
    );
  });
  const result = sorted.map(toSummary);
  return limit ? result.slice(0, limit) : result;
}

export async function getNote(slug: string): Promise<NoteDetail | null> {
  const n = NOTES.find((x) => x.slug === slug);
  if (!n) return null;
  const summary = toSummary(n);
  const links = n.links;

  // Backlinks
  const backlinks: BacklinkNote[] = NOTES.filter(
    (b) => b.slug !== slug && b.links.some((l) => l.slug === slug)
  )
    .map((b) => {
      const context = extractBacklinkContext(
        b.content,
        n.title,
        n.aliases
      );
      return { ...toSummary(b), context };
    })
    .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));

  // Prev/next by publish date
  const sorted = [...NOTES].sort((a, b) =>
    (a.publishDate ?? a.createdAt).localeCompare(b.publishDate ?? b.createdAt)
  );
  const idx = sorted.findIndex((x) => x.slug === slug);
  const prev = idx > 0 ? toSummary(sorted[idx - 1]) : null;
  const next = idx >= 0 && idx < sorted.length - 1 ? toSummary(sorted[idx + 1]) : null;

  // Related notes
  const currentTags = new Set(summary.tags);
  const currentLinkSlugs = new Set(
    links.filter((l) => l.exists).map((l) => l.slug)
  );
  const backlinkSlugs = new Set(backlinks.map((b) => b.slug));
  const related: RelatedNote[] = [];
  for (const other of NOTES) {
    if (other.slug === slug) continue;
    const otherLinkSlugs = new Set(
      other.links.filter((l) => l.exists).map((l) => l.slug)
    );
    let score = 0;
    let reason: RelatedNote["reason"] | null = null;
    const sharedTags = other.tags.filter((t) => currentTags.has(t)).length;
    if (sharedTags > 0) {
      score += sharedTags * 2;
      reason = "shared-tags";
    }
    if (!currentLinkSlugs.has(other.slug) && !backlinkSlugs.has(other.slug)) {
      let twoHop = false;
      for (const nSlug of currentLinkSlugs) {
        const neighbor = NOTES.find((x) => x.slug === nSlug);
        if (neighbor && neighbor.links.some((l) => l.slug === other.slug && l.exists)) {
          twoHop = true;
          break;
        }
      }
      if (twoHop) {
        score += 3;
        reason = "2-hop";
      }
    }
    let sharedLinks = 0;
    for (const sl of otherLinkSlugs) {
      if (currentLinkSlugs.has(sl) && sl !== other.slug && sl !== slug) {
        sharedLinks++;
      }
    }
    if (sharedLinks > 0) {
      score += sharedLinks;
      if (!reason) reason = "shared-links";
    }
    if (score > 0 && reason) {
      related.push({ ...toSummary(other), reason, score });
    }
  }
  related.sort((a, b) => b.score - a.score);

  return {
    ...summary,
    content: n.content,
    html: n.html,
    links,
    backlinks,
    related: related.slice(0, 6),
    prev,
    next,
  };
}

export async function getGraph(): Promise<GraphData> {
  const nodes: GraphNode[] = NOTES.map((n) => ({
    id: n.slug,
    title: n.title,
    tags: n.tags,
    folder: n.folder,
  }));
  const nodeIds = new Set(nodes.map((n) => n.id));
  const edges: GraphEdge[] = [];
  const seen = new Set<string>();
  for (const n of NOTES) {
    for (const l of n.links) {
      if (!nodeIds.has(l.slug) || l.slug === n.slug) continue;
      const key = `${n.slug}->${l.slug}`;
      if (seen.has(key)) continue;
      seen.add(key);
      edges.push({ source: n.slug, target: l.slug });
    }
  }
  return { nodes, edges };
}

export async function getTags(): Promise<TagInfo[]> {
  const counts = new Map<string, number>();
  for (const n of NOTES) {
    for (const t of n.tags) {
      counts.set(t, (counts.get(t) ?? 0) + 1);
      const parts = t.split("/");
      for (let i = 1; i < parts.length; i++) {
        const parent = parts.slice(0, i).join("/");
        counts.set(parent, (counts.get(parent) ?? 0) + 1);
      }
    }
  }
  return Array.from(counts.entries())
    .map(([tag, count]) => ({ tag, count }))
    .sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag));
}

export async function searchNotes(
  query: string
): Promise<(NoteSummary & { snippet: string })[]> {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results: (NoteSummary & { snippet: string })[] = [];
  for (const n of NOTES) {
    const titleLower = n.title.toLowerCase();
    const descLower = (n.description ?? "").toLowerCase();
    const contentLower = n.content.toLowerCase();
    const inTitle = titleLower.includes(q);
    const inDesc = descLower.includes(q);
    const inContent = contentLower.includes(q);
    const inTags = n.tags.some((t) => t.toLowerCase().includes(q));
    if (!inTitle && !inDesc && !inContent && !inTags) continue;
    let snippet = "";
    const idx = contentLower.indexOf(q);
    if (idx !== -1) {
      const start = Math.max(0, idx - 40);
      const end = Math.min(n.content.length, idx + q.length + 80);
      snippet =
        (start > 0 ? "…" : "") +
        n.content.slice(start, end).replace(/\s+/g, " ").trim() +
        (end < n.content.length ? "…" : "");
    } else if (n.description) {
      snippet = n.description;
    }
    results.push({ ...toSummary(n), snippet });
  }
  results.sort((a, b) => {
    const at = a.title.toLowerCase().includes(q) ? 0 : 1;
    const bt = b.title.toLowerCase().includes(q) ? 0 : 1;
    if (at !== bt) return at - bt;
    return b.updatedAt > a.updatedAt ? 1 : -1;
  });
  return results;
}

export async function getExplorer(): Promise<ExplorerNode[]> {
  const sorted = [...NOTES].sort((a, b) => {
    if (a.folder !== b.folder) return (a.folder ?? "").localeCompare(b.folder ?? "");
    return a.title.localeCompare(b.title);
  });
  const root: ExplorerNode = {
    name: "garden",
    path: "",
    type: "folder",
    children: [],
  };
  for (const n of sorted) {
    const parts = n.path.split("/").filter(Boolean);
    let cursor = root;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isFile = i === parts.length - 1;
      if (isFile) {
        cursor.children!.push({
          name: n.title,
          path: n.path,
          type: "file",
          slug: n.slug,
        });
      } else {
        let child = cursor.children!.find(
          (c) => c.type === "folder" && c.name === part
        );
        if (!child) {
          child = {
            name: part,
            path: parts.slice(0, i + 1).join("/"),
            type: "folder",
            children: [],
          };
          cursor.children!.push(child);
        }
        cursor = child;
      }
    }
  }
  const sortTree = (node: ExplorerNode) => {
    node.children!.sort((a, b) => {
      if (a.type !== b.type) return a.type === "folder" ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
    for (const c of node.children!) if (c.type === "folder") sortTree(c);
  };
  sortTree(root);
  return root.children!;
}

export async function getStats(): Promise<{
  totalNotes: number;
  totalWords: number;
  totalLinks: number;
  totalTags: number;
  lastUpdated: string | null;
}> {
  const tagSet = new Set<string>();
  let totalWords = 0;
  let totalLinks = 0;
  let lastUpdated: string | null = null;
  for (const n of NOTES) {
    totalWords += n.wordCount;
    totalLinks += n.links.length;
    for (const t of n.tags) tagSet.add(t);
    if (!lastUpdated || n.updatedAt > lastUpdated) lastUpdated = n.updatedAt;
  }
  return {
    totalNotes: NOTES.length,
    totalWords,
    totalLinks,
    totalTags: tagSet.size,
    lastUpdated,
  };
}

export async function getOnThisDay(): Promise<NoteSummary[]> {
  const now = new Date();
  const month = now.getMonth() + 1;
  const day = now.getDate();
  const year = now.getFullYear();
  return NOTES.filter((n) => {
    if (!n.publishDate) return false;
    const d = new Date(n.publishDate);
    return (
      d.getMonth() + 1 === month &&
      d.getDate() === day &&
      d.getFullYear() < year
    );
  })
    .map(toSummary)
    .sort((a, b) =>
      (b.publishDate ?? "").localeCompare(a.publishDate ?? "")
    );
}
