/**
 * telegram-task-coach.ts — Strategic AI Roadmap & Next Action Mentor
 * Sequences learning paths, identifies missing milestones, and provides execution blueprints.
 */

import { getTasksFromGitHub, addPendingTasksToGitHub } from "./telegram-file-handler";
import { listNotes } from "@/lib/notes";
import { geminiUrl } from "./ai-models";

function formatTWDueDate(dateStr: string | null): string {
  if (!dateStr) return "";
  const m = dateStr.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/);
  if (!m) return "";
  const d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +m[6]));
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Dhaka",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(d);
}

/**
 * Converts Markdown or AI generated text to Telegram-compatible HTML.
 * Safely escapes all special characters (<, >, &) inside both text and code blocks,
 * preventing Telegram API 400 parsing errors on code snippets (e.g. C++ <iostream>, templates, <<).
 */
export function markdownToTelegramHtml(text: string): string {
  if (!text) return "";

  const codeBlocks: string[] = [];

  // 1. Extract fenced code blocks (```lang\ncode\n``` or ```code```)
  let processed = text.replace(/```(?:([a-zA-Z0-9_-]+)\n)?([\s\S]*?)```/g, (_match, _lang, code) => {
    const escapedCode = (code || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    const idx = codeBlocks.length;
    codeBlocks.push(`<pre><code>${escapedCode.trim()}</code></pre>`);
    return `__TG_CODE_BLOCK_${idx}__`;
  });

  // 2. Extract inline code (`code`)
  processed = processed.replace(/`([^`\n]+)`/g, (_match, code) => {
    const escapedCode = (code || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    const idx = codeBlocks.length;
    codeBlocks.push(`<code>${escapedCode}</code>`);
    return `__TG_CODE_BLOCK_${idx}__`;
  });

  // 3. In non-code text, safely escape HTML characters
  // Escape & that isn't already part of standard entities
  processed = processed.replace(/&(?!amp;|lt;|gt;|quot;)/g, "&amp;");

  // Protect valid Telegram HTML tags generated by AI
  const allowedTags = ["b", "i", "u", "s", "strong", "em", "code", "pre", "blockquote", "tg-spoiler"];
  const validTagRegex = new RegExp(`<(/?(${allowedTags.join("|")})|a\\s+href="[^"]+?"|a\\s+href='[^']+'|/a)>`, "gi");

  const validTags: string[] = [];
  processed = processed.replace(validTagRegex, (match) => {
    const idx = validTags.length;
    validTags.push(match);
    return `__TG_VALID_TAG_${idx}__`;
  });

  // Escape all remaining < and > in regular text (e.g. #include <iostream>, x < y, <<, etc.)
  processed = processed
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // Restore valid tags (standardizing strong -> b, em -> i)
  processed = processed.replace(/__TG_VALID_TAG_(\d+)__/g, (_match, idxStr) => {
    const tag = validTags[parseInt(idxStr, 10)] || "";
    return tag
      .replace(/<strong(\s*>|\s+)/gi, "<b$1")
      .replace(/<\/strong>/gi, "</b>")
      .replace(/<em(\s*>|\s+)/gi, "<i$1")
      .replace(/<\/em>/gi, "</i>");
  });

  // 4. Convert Markdown formatting in text:
  // - Headers (# Header, ## Header, ### Header)
  processed = processed.replace(/^###?\s+(.+)$/gm, "<b>$1</b>");
  processed = processed.replace(/^##\s+(.+)$/gm, "<b>$1</b>");
  processed = processed.replace(/^#\s+(.+)$/gm, "<b>$1</b>");

  // - Bold markdown **text** or __text__
  processed = processed.replace(/\*\*(.*?)\*\*/g, "<b>$1</b>");
  processed = processed.replace(/__(.*?)__/g, "<b>$1</b>");

  // - Italic markdown *text* or _text_
  processed = processed.replace(/(^|\s)\*(.*?)\*(\s|$)/g, "$1<i>$2</i>$3");
  processed = processed.replace(/(^|\s)_(.*?)_(\s|$)/g, "$1<i>$2</i>$3");

  // - Markdown links [text](url)
  processed = processed.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2">$1</a>');

  // 5. Restore code blocks
  processed = processed.replace(/__TG_CODE_BLOCK_(\d+)__/g, (_match, idxStr) => {
    return codeBlocks[parseInt(idxStr, 10)] || "";
  });

  return processed.trim();
}

/**
 * Backward compatibility alias for markdownToTelegramHtml.
 */
export const sanitizeTelegramHtml = markdownToTelegramHtml;

export interface StrategicRoadmapResult {
  text: string;
  suggestedTasks: string[];
}

/**
 * Analyzes active tasks, digital garden context, and learning curriculum to determine:
 * 1. Immediate Next Step (in logical order)
 * 2. Step-by-step How-To execution blueprint (code/exercise/note)
 * 3. Missing Milestone Tasks that should be added to the roadmap
 */
export async function getAiNextStrategicRoadmap(customQuery?: string): Promise<StrategicRoadmapResult> {
  const today = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Dhaka",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());

  const tasksSnapshot = await getTasksFromGitHub().catch(() => null);
  const tasks = tasksSnapshot?.tasks || [];

  // Fetch recent notes and existing garden tags for knowledge compounding
  const notes = await listNotes().catch(() => []);
  const recentNotes = notes.slice(0, 10).map((n) => `[[${n.title}]] (${n.tags?.map(t => `#${t}`).join(" ") || "no tags"})`).join(", ") || "None";
  const allTags = Array.from(new Set(notes.flatMap(n => n.tags || []))).slice(0, 15).map(t => `#${t}`).join(" ");

  // Build task list summary
  const taskList = tasks.length > 0
    ? tasks.map((t, idx) => {
        const dueStr = t.due ? `due: ${formatTWDueDate(t.due)}` : "no date";
        const prioStr = t.priority ? `[Priority ${t.priority}]` : "";
        return `Task #${idx + 1}: "${t.description}" (Project: ${t.project || "general"}, ${dueStr}, ${prioStr})`;
      }).join("\n")
    : "No active tasks in Taskwarrior yet.";

  const geminiKey = (process.env.GEMINI_API_KEY || process.env.GOOGLE_AI_KEY || "").trim();
  const groqKey = (process.env.GROQ_API_KEY || "").trim();

  const systemPrompt = `You are a world-class principal software engineer and cognitive learning mentor for Ridoy's digital garden ("xnocode").

Your Mission:
Design an intelligent, highly disciplined, and continuous BATTLE PLAN & LEARNING GUIDE for the student's daily study session.

Core Pedagogical Principles you MUST enforce:
1. STRICT PREREQUISITE SEQUENCING (No Skipping):
   - Review their active tasks in order. Foundation and setup must precede advanced topics (e.g. Task #1 Intro/Setup before Variables; Variables before Conditionals; Conditionals before Loops).
   - If earlier tasks in a track are pending, pick the TRUE root prerequisite as today's exact task.
2. 3-STAGE COMPOUNDING LEARNING LOOP (Total ~45 mins):
   - Phase A: Core Mental Model (15m) — Concrete theory and mental model, avoiding passive reading.
   - Phase B: Active Compiler / Problem Practice (20m) — A practical, concise 5-10 line code snippet to write, test, and observe edge cases.
   - Phase C: Digital Garden Compounding (10m) — Exact Obsidian note with [[wikilinks]], #tags, connecting new knowledge to their existing garden notes (e.g. comparing C++ static types with their Python notes or linking to DSA).
3. CONTINUITY & FRICTION REDUCTION:
   - Provide "Tomorrow's On-Ramp" (the exact milestone/checkpoint that will unlock next).
4. ACADEMIC & TRACK BALANCING:
   - Balance their main programming track (C++) with their University studies (Semester 4: Fourier Analysis, DSA-II, Software Engineering).

Formatting Rules:
- Put all code snippets inside standard markdown code blocks (\`\`\`cpp ... \`\`\`). Keep code concise (~5-10 lines).
- Use clean Markdown (**bold**, *italic*, \`inline code\`). Use clean emojis.
- For missing critical milestones, put lines at the very end like:
  [SUGGESTED_TASK: CPP - Functions & Scope priority:H project:cpp]
  [SUGGESTED_TASK: CPP - Pointers & Memory Management priority:H project:cpp]`;

  const userPrompt = `Current Date: ${today}
Student's Current Active Tasks:
${taskList}

Digital Garden Existing Tags & Knowledge Base:
Tags: ${allTags || "#cpp #university #aiml #garden"}
Recent Notes in Garden: ${recentNotes}

${customQuery ? `Student's Focus / Request: "${customQuery}"` : "Analyze my tasks and provide a deep, disciplined learning guide: What exact prerequisite task must I do right now, the 3-stage practice loop, how it connects to my garden, and the sequenced path forward."}

Format the response cleanly:
🗺️ **Strategic Action Plan & Deep Learning Guide**

🧭 **1. Active Track & Sprint Goal:**
[1-2 sentences on current sprint focus, e.g. C++ Systems Track: Stage 1 Primitives & University Math]

🌟 **2. EXACT TASK TO DO RIGHT NOW:**
• **[Task Name & Number]** *(Est: ~45 mins)*
💡 *Pedagogical Reason:* [Why this foundational step comes before all following tasks]

🛠️ **3. 3-Stage Compounding Execution Guide:**
• 📖 **Phase A: Mental Model (15m):** [Core concept to internalize without distraction]
• 💻 **Phase B: Active Practice & Edge Cases (20m):**
\`\`\`cpp
// 5-10 lines runnable code exercise
\`\`\`
• 📝 **Phase C: Digital Garden Compounding (10m):** Write note \`[[Note Title]]\` with tags \`#tag1 #tag2\`, cross-linking with existing concepts.

⚡ **4. Sequenced Roadmap (Chronological Milestones):**
1. ⏩ **[Immediate Follow-up Task]** — [Next milestone]
2. ⏩ **[Secondary Follow-up Task]** — [Following milestone]
3. ⏩ **[Tertiary Milestone]** — [Track progression]

🎯 **5. Tomorrow's Frictionless On-Ramp:**
[1 clear sentence stating the exact condition/trigger to start tomorrow's session seamlessly]

💡 **6. Missing Milestones to Add to Roadmap:**
• **[Suggested Task 1]** — [Why it's essential for mastery]
• **[Suggested Task 2]** — [Why it's essential for mastery]

[SUGGESTED_TASK: <Task 1 with priority and project>]
[SUGGESTED_TASK: <Task 2 with priority and project>]`;

  let responseText = "";

  // 1. Try Gemini
  if (geminiKey) {
    try {
      const res = await fetch(geminiUrl(geminiKey), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: `${systemPrompt}\n\n${userPrompt}` }] }],
          generationConfig: { temperature: 0.4, maxOutputTokens: 1600 },
        }),
      });

      if (res.ok) {
        const data = await res.json();
        const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (rawText) responseText = rawText;
      }
    } catch (err: any) {
      console.warn("Gemini strategic roadmap failed:", err.message);
    }
  }

  // 2. Try Groq Llama Fallback
  if (!responseText && groqKey) {
    try {
      const gRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${groqKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.4,
          max_tokens: 1600,
        }),
      });

      if (gRes.ok) {
        const gData = await gRes.json();
        const content = gData?.choices?.[0]?.message?.content;
        if (content) responseText = content;
      }
    } catch (err: any) {
      console.warn("Groq strategic roadmap failed:", err.message);
    }
  }

  // Parse suggested tasks from [SUGGESTED_TASK: ...] tags
  const suggestedTasks: string[] = [];
  if (responseText) {
    const matches = responseText.matchAll(/\[SUGGESTED_TASK:\s*(.+?)\]/g);
    for (const match of matches) {
      if (match[1]) {
        suggestedTasks.push(match[1].trim());
      }
    }
    // Remove the raw metadata tags from user-facing text
    responseText = responseText.replace(/\[SUGGESTED_TASK:\s*.+?\]/g, "").trim();
    return {
      text: markdownToTelegramHtml(responseText),
      suggestedTasks,
    };
  }

  // 3. Fallback Roadmap
  return {
    text: markdownToTelegramHtml(
      `🗺️ **Strategic Action Plan & Roadmap**\n\n` +
      `🧭 **1. Current Focus & Sprint Goal:**\n` +
      `Mastering **C++ Programming Foundations** (Variables, Operators, Control Flow) alongside **University Math**.\n\n` +
      `🌟 **2. EXACT TASK TO DO RIGHT NOW:**\n` +
      `• **Task #1: CPP - Introduction & Setup** *(Est: ~30 mins)*\n` +
      `💡 *Why this first:* Validates your build environment (compiler, debugger) before writing application logic.\n\n` +
      `🛠️ **3. Step-by-Step Execution Guide:**\n` +
      `• 📖 **Core Concept (10m):** Compilation pipeline (source -> preprocessor -> compiler -> linker -> binary).\n` +
      `• 💻 **Code / Practice Exercise (15m):**\n` +
      `\`\`\`cpp\n` +
      `#include <iostream>\n` +
      `int main() {\n` +
      `    std::cout << "C++ Environment Ready!" << std::endl;\n` +
      `    return 0;\n` +
      `}\n` +
      `\`\`\`\n` +
      `• 📝 **Digital Garden Note (10m):** Create \`[[C++ Compilation Model]]\` with tags \`#cpp #foundations\`.\n\n` +
      `⚡ **4. Sequenced Roadmap:**\n` +
      `1. ⏩ **CPP - Variables & Data Types** — Memory sizes and type safety.\n` +
      `2. ⏩ **CPP - Operators & Logic** — Arithmetic, relational, and bitwise expressions.\n` +
      `3. ⏩ **CPP - Conditional Statements & Loops** — Branching, iteration, and control flow.\n` +
      `4. ⏩ **University Math: Fourier Analysis** — Complex variables and frequency domain.\n\n` +
      `💡 **5. Missing Milestones to Add:**\n` +
      `• **CPP - Functions & Scope** — Modular programming and stack frames.\n` +
      `• **CPP - Pointers & Memory Management** — Direct memory addressing and references.`
    ),
    suggestedTasks: [
      "CPP - Functions & Scope priority:H project:cpp",
      "CPP - Pointers & References priority:H project:cpp",
      "CPP - Mini Project: Number Guessing Game priority:M project:cpp",
    ],
  };
}

/**
 * Generates an on-demand 3-step Neural Study Blueprint for any given topic or task.
 */
export async function getTaskStudyBlueprint(topicOrTask: string): Promise<string> {
  const geminiKey = (process.env.GEMINI_API_KEY || process.env.GOOGLE_AI_KEY || "").trim();
  const groqKey = (process.env.GROQ_API_KEY || "").trim();

  const systemPrompt = `You are an elite cognitive learning coach. Given a study topic or task, break it down into an executive 3-step AI Neural Learning Protocol (Total 40 minutes):
1. 📖 Step 1: Input & Concept Focus (15 mins) — exactly what specific sub-concept to absorb without distractions.
2. ⚡ Step 2: Active Recall Test (5 mins) — exact closed-screen recall questions to test memory from scratch.
3. 🛠️ Step 3: 30/70 Practice & Build (20 mins) — exact concrete mini-project, code snippet, or Obsidian note to produce.
4. 🧠 Long-Term Memory Anchor — 1 practical analogy or memory hook.

Format using clean Markdown (**bold**, *italic*, \`code\`, and \`\`\` code blocks). Keep code snippets concise.`;

  const userPrompt = `Topic or Task to study: "${topicOrTask}"`;

  if (geminiKey) {
    try {
      const res = await fetch(geminiUrl(geminiKey), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: `${systemPrompt}\n\n${userPrompt}` }] }],
          generationConfig: { temperature: 0.6, maxOutputTokens: 900 },
        }),
      });

      if (res.ok) {
        const data = await res.json();
        const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (rawText) return sanitizeTelegramHtml(rawText);
      }
    } catch (err: any) {
      console.warn("Gemini study blueprint failed:", err.message);
    }
  }

  if (groqKey) {
    try {
      const gRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${groqKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.6,
          max_tokens: 900,
        }),
      });

      if (gRes.ok) {
        const gData = await gRes.json();
        const content = gData?.choices?.[0]?.message?.content;
        if (content) return sanitizeTelegramHtml(content);
      }
    } catch (err: any) {
      console.warn("Groq study blueprint failed:", err.message);
    }
  }

  return (
    `🧠 <b>AI Neural Study Blueprint: ${topicOrTask}</b>\n\n` +
    `📖 <b>1. Focused Input (15 mins):</b>\n` +
    `Read or watch only the single immediate sub-concept. Do not multitask.\n\n` +
    `⚡ <b>2. Active Recall (5 mins):</b>\n` +
    `Close everything. Write down how it works in your own words on a blank sheet of paper.\n\n` +
    `🛠️ <b>3. Output / Practice (20 mins):</b>\n` +
    `Write 2 working code examples or an Obsidian note with <code>[[wikilinks]]</code>.\n\n` +
    `💡 <i>"Mastery comes from retrieval practice, not passive review."</i>`
  );
}

/**
 * Backward compatibility helper for daily plan
 */
export async function getAiNextDayGuidance(customQuery?: string): Promise<{ text: string }> {
  const result = await getAiNextStrategicRoadmap(customQuery);
  return { text: result.text };
}
