/**
 * telegram-task-coach.ts — Strategic AI Roadmap & Next Action Mentor
 * Sequences learning paths, identifies missing milestones, and provides execution blueprints.
 */

import { getTasksFromGitHub, addPendingTasksToGitHub } from "./telegram-file-handler";
import { listNotes } from "@/lib/notes";
import { geminiUrl } from "./ai-models";

function formatTWDueDate(dateStr: string | null): string {
  if (!dateStr) return "";
  const m = dateStr.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/);
  if (!m) return "";
  const d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +m[6]));
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Dhaka",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(d);
}

/**
 * Converts Markdown or AI generated text to Telegram-compatible HTML.
 * Safely escapes all special characters (<, >, &) inside both text and code blocks,
 * preventing Telegram API 400 parsing errors on code snippets (e.g. C++ <iostream>, templates, <<).
 */
export function markdownToTelegramHtml(text: string): string {
  if (!text) return "";

  const codeBlocks: string[] = [];

  // 1. Extract fenced code blocks (```lang\ncode\n``` or ```code```)
  let processed = text.replace(/```(?:([a-zA-Z0-9_-]+)\n)?([\s\S]*?)```/g, (_match, _lang, code) => {
    const escapedCode = (code || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    const idx = codeBlocks.length;
    codeBlocks.push(`<pre><code>${escapedCode.trim()}</code></pre>`);
    return `__TG_CODE_BLOCK_${idx}__`;
  });

  // 2. Extract inline code (`code`)
  processed = processed.replace(/`([^`\n]+)`/g, (_match, code) => {
    const escapedCode = (code || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    const idx = codeBlocks.length;
    codeBlocks.push(`<code>${escapedCode}</code>`);
    return `__TG_CODE_BLOCK_${idx}__`;
  });

  // 3. Convert markdown list bullets (* or - at start of line) to • so they are never mistaken for italic tags
  processed = processed.replace(/^[\*\-]\s+/gm, "• ");
  processed = processed.replace(/^\s{2,}[\*\-]\s+/gm, "    • ");

  // 4. Convert horizontal dividers (---, ***, ___)
  processed = processed.replace(/^[-*_]{3,}\s*$/gm, "───────────────────────────");

  // 5. In non-code text, safely escape HTML characters
  // Escape & that isn't already part of standard entities
  processed = processed.replace(/&(?!amp;|lt;|gt;|quot;)/g, "&amp;");

  // Protect valid Telegram HTML tags generated by AI
  const allowedTags = ["b", "i", "u", "s", "strong", "em", "code", "pre", "blockquote", "tg-spoiler"];
  const validTagRegex = new RegExp(`<(/?(${allowedTags.join("|")})|a\\s+href="[^"]+?"|a\\s+href='[^']+'|/a)>`, "gi");

  const validTags: string[] = [];
  processed = processed.replace(validTagRegex, (match) => {
    const idx = validTags.length;
    validTags.push(match);
    return `__TG_VALID_TAG_${idx}__`;
  });

  // Escape all remaining < and > in regular text (e.g. #include <iostream>, x < y, <<, etc.)
  processed = processed
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // Restore valid tags (standardizing strong -> b, em -> i)
  processed = processed.replace(/__TG_VALID_TAG_(\d+)__/g, (_match, idxStr) => {
    const tag = validTags[parseInt(idxStr, 10)] || "";
    return tag
      .replace(/<strong(\s*>|\s+)/gi, "<b$1")
      .replace(/<\/strong>/gi, "</b>")
      .replace(/<em(\s*>|\s+)/gi, "<i$1")
      .replace(/<\/em>/gi, "</i>");
  });

  // 6. Convert Markdown formatting in text (strictly single-line to avoid multi-line eating):
  // - Headers (# Header, ## Header, ### Header)
  processed = processed.replace(/^###?\s+(.+)$/gm, "<b>$1</b>");
  processed = processed.replace(/^##\s+(.+)$/gm, "<b>$1</b>");
  processed = processed.replace(/^#\s+(.+)$/gm, "<b>$1</b>");

  // - Bold markdown **text** or __text__ (non-greedy, single line)
  processed = processed.replace(/\*\*([^\n*]+?)\*\*/g, "<b>$1</b>");
  processed = processed.replace(/__([^\n_]+?)__/g, "<b>$1</b>");

  // - Italic markdown *text* or _text_ (non-greedy, single line)
  processed = processed.replace(/(^|[^\w*])\*([^\n*]+?)\*([^\w*]|$)/g, "$1<i>$2</i>$3");
  processed = processed.replace(/(^|[^\w_])_([^\n_]+?)_([^\w_]|$)/g, "$1<i>$2</i>$3");

  // - Markdown links [text](url)
  processed = processed.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2">$1</a>');

  // 7. Restore code blocks
  processed = processed.replace(/__TG_CODE_BLOCK_(\d+)__/g, (_match, idxStr) => {
    return codeBlocks[parseInt(idxStr, 10)] || "";
  });

  return processed.trim();
}

/**
 * Backward compatibility alias for markdownToTelegramHtml.
 */
export const sanitizeTelegramHtml = markdownToTelegramHtml;

/**
 * Generates an on-demand 3-step Neural Study Blueprint for any given topic or task.
 */
export async function getTaskStudyBlueprint(topicOrTask: string): Promise<string> {
  const geminiKey = (process.env.GEMINI_API_KEY || process.env.GOOGLE_AI_KEY || "").trim();
  const groqKey = (process.env.GROQ_API_KEY || "").trim();

  const systemPrompt = `You are an elite cognitive learning coach. Given a study topic or task, break it down into an executive 3-step AI Neural Learning Protocol (Total 40 minutes):
1. 📖 Step 1: Input & Concept Focus (15 mins) — exactly what specific sub-concept to absorb without distractions.
2. ⚡ Step 2: Active Recall Test (5 mins) — exact closed-screen recall questions to test memory from scratch.
3. 🛠️ Step 3: 30/70 Practice & Build (20 mins) — exact concrete mini-project, code snippet, or Obsidian note to produce.
4. 🧠 Long-Term Memory Anchor — 1 practical analogy or memory hook.

Format using clean Markdown (**bold**, *italic*, \`code\`, and \`\`\` code blocks). Keep code snippets concise.`;

  const userPrompt = `Topic or Task to study: "${topicOrTask}"`;

  if (geminiKey) {
    try {
      const res = await fetch(geminiUrl(geminiKey), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: `${systemPrompt}\n\n${userPrompt}` }] }],
          generationConfig: { temperature: 0.6, maxOutputTokens: 900 },
        }),
      });

      if (res.ok) {
        const data = await res.json();
        const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (rawText) return markdownToTelegramHtml(rawText);
      }
    } catch (err: any) {
      console.warn("Gemini study blueprint failed:", err.message);
    }
  }

  if (groqKey) {
    try {
      const gRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${groqKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.6,
          max_tokens: 900,
        }),
      });

      if (gRes.ok) {
        const gData = await gRes.json();
        const content = gData?.choices?.[0]?.message?.content;
        if (content) return markdownToTelegramHtml(content);
      }
    } catch (err: any) {
      console.warn("Groq study blueprint failed:", err.message);
    }
  }

  return (
    `🧠 <b>AI Neural Study Blueprint: ${topicOrTask}</b>\n\n` +
    `📖 <b>1. Focused Input (15 mins):</b>\n` +
    `Read or watch only the single immediate sub-concept. Do not multitask.\n\n` +
    `⚡ <b>2. Active Recall (5 mins):</b>\n` +
    `Close everything. Write down how it works in your own words on a blank sheet of paper.\n\n` +
    `🛠️ <b>3. Output / Practice (20 mins):</b>\n` +
    `Write 2 working code examples or an Obsidian note with <code>[[wikilinks]]</code>.\n\n` +
    `💡 <i>"Mastery comes from retrieval practice, not passive review."</i>`
  );
}
